// @flow

export const FETCH_DATALOG_DATA = "FETCH_DATALOG_DATA";
export const REQUEST_DATALOG_DATA = "REQUEST_DATALOG_DATA";
export const RECEIVE_DATALOG_DATA = "RECEIVE_DATALOG_DATA";
export const REQUEST_AWS_DATA = "REQUEST_AWS_DATA";
export const RECEIVE_AWS_DATA = "RECEIVE_AWS_DATA";

